###
GET {{url}}/hello/say

###
GET {{url}}/spring/caching/addDog

###
GET {{url}}/spring/caching/updateDog

###
GET {{url}}/spring/caching/deleteDog

###
GET {{url}}/spring/caching/getDog

###
POST {{url}}/spring/aop/test
Content-Type: application/json

{
  "username": "ispong"
}